const KANTO_TYPES = [
  "Normal", "Feu", "Eau", "Electrik", "Plante", "Glace", "Combat", "Poison",
  "Sol", "Vol", "Psy", "Insecte", "Roche", "Spectre", "Dragon", "Tenebres",
  "Acier", "Fee"
];

const TYPE_COLORS = {
  Normal: "#a8a878",
  Feu: "#f08030",
  Eau: "#6890f0",
  Electrik: "#f8d030",
  Plante: "#78c850",
  Glace: "#98d8d8",
  Combat: "#c03028",
  Poison: "#a040a0",
  Sol: "#e0c068",
  Vol: "#a890f0",
  Psy: "#f85888",
  Insecte: "#a8b820",
  Roche: "#b8a038",
  Spectre: "#705898",
  Dragon: "#7038f8",
  Tenebres: "#705848",
  Acier: "#b8b8d0",
  Fee: "#ee99ac"
};

const TYPE_ICONS = {
  Normal: "#",
  Feu: "^",
  Eau: "~",
  Electrik: "!",
  Plante: "*",
  Glace: "+",
  Combat: "x",
  Poison: "%",
  Sol: "_",
  Vol: ">",
  Psy: "?",
  Insecte: "::",
  Roche: "[]",
  Spectre: "()",
  Dragon: ">>",
  Tenebres: "//",
  Acier: "=",
  Fee: "+"
};

const TYPE_LOGOS = {
  Normal: "data/normal.png",
  Feu: "data/feu.png",
  Eau: "data/eau.png",
  Electrik: "data/electrik.png",
  Plante: "data/plante.png",
  Glace: "data/glace.png",
  Combat: "data/combat.png",
  Poison: "data/poison.png",
  Sol: "data/sol.png",
  Vol: "data/vol.png",
  Psy: "data/psy.png",
  Insecte: "data/insecte.png",
  Roche: "data/roche.png",
  Spectre: "data/spectre.png",
  Dragon: "data/dragon.png",
  Tenebres: "data/tenebre.png",
  Acier: "data/metal.png",
  Fee: "data/fée.png"
};

const ATTACK_CHART = {
  Normal: { Roche: 0.5, Spectre: 0, Acier: 0.5 },
  Feu: { Feu: 0.5, Eau: 0.5, Plante: 2, Glace: 2, Insecte: 2, Roche: 0.5, Dragon: 0.5, Acier: 2 },
  Eau: { Feu: 2, Eau: 0.5, Plante: 0.5, Sol: 2, Roche: 2, Dragon: 0.5 },
  Electrik: { Eau: 2, Electrik: 0.5, Plante: 0.5, Sol: 0, Vol: 2, Dragon: 0.5 },
  Plante: { Feu: 0.5, Eau: 2, Plante: 0.5, Poison: 0.5, Sol: 2, Vol: 0.5, Insecte: 0.5, Roche: 2, Dragon: 0.5, Acier: 0.5 },
  Glace: { Feu: 0.5, Eau: 0.5, Plante: 2, Glace: 0.5, Sol: 2, Vol: 2, Dragon: 2, Acier: 0.5 },
  Combat: { Normal: 2, Glace: 2, Poison: 0.5, Vol: 0.5, Psy: 0.5, Insecte: 0.5, Roche: 2, Spectre: 0, Tenebres: 2, Acier: 2, Fee: 0.5 },
  Poison: { Plante: 2, Poison: 0.5, Sol: 0.5, Roche: 0.5, Spectre: 0.5, Acier: 0, Fee: 2 },
  Sol: { Feu: 2, Electrik: 2, Plante: 0.5, Poison: 2, Vol: 0, Insecte: 0.5, Roche: 2, Acier: 2 },
  Vol: { Electrik: 0.5, Plante: 2, Combat: 2, Insecte: 2, Roche: 0.5, Acier: 0.5 },
  Psy: { Combat: 2, Poison: 2, Psy: 0.5, Tenebres: 0, Acier: 0.5 },
  Insecte: { Feu: 0.5, Plante: 2, Combat: 0.5, Poison: 0.5, Vol: 0.5, Psy: 2, Spectre: 0.5, Tenebres: 2, Acier: 0.5, Fee: 0.5 },
  Roche: { Feu: 2, Glace: 2, Combat: 0.5, Sol: 0.5, Vol: 2, Insecte: 2, Acier: 0.5 },
  Spectre: { Normal: 0, Psy: 2, Spectre: 2, Tenebres: 0.5 },
  Dragon: { Dragon: 2, Acier: 0.5, Fee: 0 },
  Tenebres: { Combat: 0.5, Psy: 2, Spectre: 2, Tenebres: 0.5, Fee: 0.5 },
  Acier: { Feu: 0.5, Eau: 0.5, Electrik: 0.5, Glace: 2, Roche: 2, Acier: 0.5, Fee: 2 },
  Fee: { Feu: 0.5, Combat: 2, Poison: 0.5, Dragon: 2, Tenebres: 2, Acier: 0.5 }
};

const KANTO_POKEMON = [
  ["Bulbizarre", "Plante", "Poison"],
  ["Herbizarre", "Plante", "Poison"],
  ["Florizarre", "Plante", "Poison"],
  ["Salameche", "Feu"],
  ["Reptincel", "Feu"],
  ["Dracaufeu", "Feu", "Vol"],
  ["Carapuce", "Eau"],
  ["Carabaffe", "Eau"],
  ["Tortank", "Eau"],
  ["Chenipan", "Insecte"],
  ["Chrysacier", "Insecte"],
  ["Papilusion", "Insecte", "Vol"],
  ["Aspicot", "Insecte", "Poison"],
  ["Coconfort", "Insecte", "Poison"],
  ["Dardargnan", "Insecte", "Poison"],
  ["Roucool", "Normal", "Vol"],
  ["Roucoups", "Normal", "Vol"],
  ["Roucarnage", "Normal", "Vol"],
  ["Rattata", "Normal"],
  ["Rattatac", "Normal"],
  ["Piafabec", "Normal", "Vol"],
  ["Rapasdepic", "Normal", "Vol"],
  ["Abo", "Poison"],
  ["Arbok", "Poison"],
  ["Pikachu", "Electrik"],
  ["Raichu", "Electrik"],
  ["Sabelette", "Sol"],
  ["Sablaireau", "Sol"],
  ["Nidoran F", "Poison"],
  ["Nidorina", "Poison"],
  ["Nidoqueen", "Poison", "Sol"],
  ["Nidoran M", "Poison"],
  ["Nidorino", "Poison"],
  ["Nidoking", "Poison", "Sol"],
  ["Melofee", "Fee"],
  ["Melodelfe", "Fee"],
  ["Goupix", "Feu"],
  ["Feunard", "Feu"],
  ["Rondoudou", "Normal", "Fee"],
  ["Grodoudou", "Normal", "Fee"],
  ["Nosferapti", "Poison", "Vol"],
  ["Nosferalto", "Poison", "Vol"],
  ["Mystherbe", "Plante", "Poison"],
  ["Ortide", "Plante", "Poison"],
  ["Rafflesia", "Plante", "Poison"],
  ["Paras", "Insecte", "Plante"],
  ["Parasect", "Insecte", "Plante"],
  ["Mimitoss", "Insecte", "Poison"],
  ["Aeromite", "Insecte", "Poison"],
  ["Taupiqueur", "Sol"],
  ["Triopikeur", "Sol"],
  ["Miaouss", "Normal"],
  ["Persian", "Normal"],
  ["Psykokwak", "Eau"],
  ["Akwakwak", "Eau"],
  ["Ferosinge", "Combat"],
  ["Colossinge", "Combat"],
  ["Caninos", "Feu"],
  ["Arcanin", "Feu"],
  ["Ptitard", "Eau"],
  ["Tetarte", "Eau"],
  ["Tartard", "Eau", "Combat"],
  ["Abra", "Psy"],
  ["Kadabra", "Psy"],
  ["Alakazam", "Psy"],
  ["Machoc", "Combat"],
  ["Machopeur", "Combat"],
  ["Mackogneur", "Combat"],
  ["Chetiflor", "Plante", "Poison"],
  ["Boustiflor", "Plante", "Poison"],
  ["Empiflor", "Plante", "Poison"],
  ["Tentacool", "Eau", "Poison"],
  ["Tentacruel", "Eau", "Poison"],
  ["Racaillou", "Roche", "Sol"],
  ["Gravalanch", "Roche", "Sol"],
  ["Grolem", "Roche", "Sol"],
  ["Ponyta", "Feu"],
  ["Galopa", "Feu"],
  ["Ramoloss", "Eau", "Psy"],
  ["Flagadoss", "Eau", "Psy"],
  ["Magneti", "Electrik", "Acier"],
  ["Magneton", "Electrik", "Acier"],
  ["Canarticho", "Normal", "Vol"],
  ["Doduo", "Normal", "Vol"],
  ["Dodrio", "Normal", "Vol"],
  ["Otaria", "Eau"],
  ["Lamantine", "Eau", "Glace"],
  ["Tadmorv", "Poison"],
  ["Grotadmorv", "Poison"],
  ["Kokiyas", "Eau"],
  ["Crustabri", "Eau", "Glace"],
  ["Fantominus", "Spectre", "Poison"],
  ["Spectrum", "Spectre", "Poison"],
  ["Ectoplasma", "Spectre", "Poison"],
  ["Onix", "Roche", "Sol"],
  ["Soporifik", "Psy"],
  ["Hypnomade", "Psy"],
  ["Krabby", "Eau"],
  ["Krabboss", "Eau"],
  ["Voltorbe", "Electrik"],
  ["Electrode", "Electrik"],
  ["Noeunoeuf", "Plante", "Psy"],
  ["Noadkoko", "Plante", "Psy"],
  ["Osselait", "Sol"],
  ["Ossatueur", "Sol"],
  ["Kicklee", "Combat"],
  ["Tygnon", "Combat"],
  ["Excelangue", "Normal"],
  ["Smogo", "Poison"],
  ["Smogogo", "Poison"],
  ["Rhinocorne", "Sol", "Roche"],
  ["Rhinoferos", "Sol", "Roche"],
  ["Leveinard", "Normal"],
  ["Saquedeneu", "Plante"],
  ["Kangourex", "Normal"],
  ["Hypotrempe", "Eau"],
  ["Hypocean", "Eau"],
  ["Poissirene", "Eau"],
  ["Poissoroy", "Eau"],
  ["Stari", "Eau"],
  ["Staross", "Eau", "Psy"],
  ["M. Mime", "Psy", "Fee"],
  ["Insecateur", "Insecte", "Vol"],
  ["Lippoutou", "Glace", "Psy"],
  ["Elektek", "Electrik"],
  ["Magmar", "Feu"],
  ["Scarabrute", "Insecte"],
  ["Tauros", "Normal"],
  ["Magicarpe", "Eau"],
  ["Leviator", "Eau", "Vol"],
  ["Lokhlass", "Eau", "Glace"],
  ["Metamorph", "Normal"],
  ["Evoli", "Normal"],
  ["Aquali", "Eau"],
  ["Voltali", "Electrik"],
  ["Pyroli", "Feu"],
  ["Porygon", "Normal"],
  ["Amonita", "Roche", "Eau"],
  ["Amonistar", "Roche", "Eau"],
  ["Kabuto", "Roche", "Eau"],
  ["Kabutops", "Roche", "Eau"],
  ["Ptera", "Roche", "Vol"],
  ["Ronflex", "Normal"],
  ["Artikodin", "Glace", "Vol"],
  ["Electhor", "Electrik", "Vol"],
  ["Sulfura", "Feu", "Vol"],
  ["Minidraco", "Dragon"],
  ["Draco", "Dragon"],
  ["Dracolosse", "Dragon", "Vol"],
  ["Mewtwo", "Psy"],
  ["Mew", "Psy"]
].map((entry, index) => ({
  id: index + 1,
  name: entry[0],
  types: entry.slice(1),
  custom: false
}));
